### ISSUE TITLE
Oh, my god. The decoder seems strange.

### ISSUE THREAD

**Issue by xiesiyuan** [xunhuang1995/AdaIN-style#1]
![me_stylized_toka](https://cloud.githubusercontent.com/assets/19420138/24160180/2432ea94-0e9c-11e7-8e38-d9b23c0b00c5.jpg)

what has happened???

**Comment by xiesiyuan** [comment]
my face always seems like ghost.... 

I think the decoder is broken.

**Comment by xunhuang1995** [comment]
The decoder is not broken. The output is probably too stylized given your style image, so that the content is not well preserved.

Below are some things you may want to try to get better results:
1. turn down `-alpha` a little bit
2. increase the resolution of the content image
3. I just uploaded a decoder with smaller style weight during training, you might like that one a bit more:
``wget -c https://s3.amazonaws.com/xunhuang-public/adain/decoder-content-similar.t7``
4. If none of the above works, try to change the style image.
