### ISSUE TITLE
Cpu - resolution

### ISSUE THREAD

**Issue by Sugarbank** [xunhuang1995/AdaIN-style#2]
Hi is it possible to run on CPU only?
Is it possible to run on large content images?

**Comment by xunhuang1995** [comment]
CPU: Yes, use `-gpu -1`
Large content images: Yes when using CPU. Should also be a yes when using GPU because feed-forward inference doesn't really need much memory. However in the implementation of torch.nn the intermediate features are always stored, which wastes lots of memory during inference. So currently the network may have some problem for large content images. I will try to fix this with [optimize-net](https://github.com/fmassa/optimize-net).
